In [75]:
# notebooks/1_data_exploration.ipynb

import os
import pandas as pd

In [76]:
# Define paths
root_data_dir = '../data/processed'

In [77]:
# Load a sample dataset (can explore others based on task)
tasks_data_df = pd.read_parquet(os.path.join(root_data_dir, 'base.parquet'))

In [78]:
# View the first few rows of the dataset
tasks_data_df.head(3)

,task_type,task_format,question,label,gold,corpus,rationale,knowledge,split
0,arc_c,multiple_choice,The day before the class is going to do a lab ...,B,to prevent injury to toes or feet,The day before the class is going to do a lab ...,,,train
1,arc_c,multiple_choice,Which mixture contains ingredients that can be...,B,fruit salad,Which mixture contains ingredients that can be...,,,train
2,arc_c,multiple_choice,"In 2005, a team of scientists discovered a pho...",B,The hydrothermal vent emits usable light.,"In 2005, a team of scientists discovered a pho...",,,train

In [79]:
# Check data types and missing values for each column
print(tasks_data_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3235 entries, 0 to 3234
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   task_type    3235 non-null   object
 1   task_format  3235 non-null   object
 2   question     3235 non-null   object
 3   label        3235 non-null   object
 4   gold         3235 non-null   object
 5   corpus       3235 non-null   object
 6   rationale    3235 non-null   object
 7   knowledge    3235 non-null   object
 8   split        3235 non-null   object
dtypes: object(9)
memory usage: 227.6+ KB
None

In [80]:
tasks_data_df[tasks_data_df['task_type']=='winogrande'].head(5)

,task_type,task_format,question,label,gold,corpus,rationale,knowledge,split
2979,winogrande,multiple_choice,Mary traded the jelly beans for the chocolate ...,A,jelly beans,Mary traded the jelly beans for the chocolate ...,,,train
2980,winogrande,multiple_choice,I went to Thailand to have the treatment and n...,A,treatment,I went to Thailand to have the treatment and n...,,,train
2981,winogrande,multiple_choice,Dennis felt a lot of guilt about lying but Bri...,B,Brian,Dennis felt a lot of guilt about lying but Bri...,,,train
2982,winogrande,multiple_choice,The draining discussion was followed by a live...,A,discussion,The draining discussion was followed by a live...,,,train
2983,winogrande,multiple_choice,Mark was in the drill of gathering proof that ...,A,proof,Mark was in the drill of gathering proof that ...,,,train

In [82]:
print(tasks_data_df[tasks_data_df['task_type']=='winogrande'].iloc[4,5])

Mark was in the drill of gathering proof that proved his company engaged in Age Discrimination but the proof was not sufficient.