In [13]:
# notebooks/1_data_exploration.ipynb

import os
import pandas as pd

In [14]:
# Define paths
root_data_dir = '../data/processed'

In [15]:
# Load a sample dataset (can explore others based on task)
tasks_data_df = pd.read_parquet(os.path.join(root_data_dir, 'final_with_prompts.parquet'))

In [16]:
# View the first few rows of the dataset
tasks_data_df.head(3)

,task_type,task_format,question,label,gold,corpus,rationale,knowledge,split,prompt_zero_shot,prompt_cot,prompt_icl,prompt_icl_cot
0,arc_c,multiple_choice,The day before the class is going to do a lab ...,B,to prevent injury to toes or feet,The day before the class is going to do a lab ...,Explanation: \nThe teacher's instruction not ...,Students are advised not to wear open-toed sho...,train,Question: The day before the class is going to...,Question: The day before the class is going to...,\n\nQuestion: The day before the class is goin...,\n\nQuestion: The day before the class is goin...
1,arc_c,multiple_choice,Which mixture contains ingredients that can be...,B,fruit salad,Which mixture contains ingredients that can be...,Explanation: \nTo determine which mixture con...,A fruit salad is a mixture in which the indivi...,train,Question: Which mixture contains ingredients t...,Question: Which mixture contains ingredients t...,\n\nQuestion: Which mixture contains ingredien...,\n\nQuestion: Which mixture contains ingredien...
2,arc_c,multiple_choice,"In 2005, a team of scientists discovered a pho...",B,The hydrothermal vent emits usable light.,"In 2005, a team of scientists discovered a pho...",Explanation: \n1. Photosynthesis is the proce...,"In 2005, scientists discovered photosynthetic ...",train,"Question: In 2005, a team of scientists discov...","Question: In 2005, a team of scientists discov...","Question: In a series of chemical reactions, X...","Question: In a series of chemical reactions, X..."

In [17]:
# Check data types and missing values for each column
print(tasks_data_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3235 entries, 0 to 3234
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   task_type         3235 non-null   object
 1   task_format       3235 non-null   object
 2   question          3235 non-null   object
 3   label             3235 non-null   object
 4   gold              3235 non-null   object
 5   corpus            3235 non-null   object
 6   rationale         3235 non-null   object
 7   knowledge         3235 non-null   object
 8   split             3235 non-null   object
 9   prompt_zero_shot  3235 non-null   object
 10  prompt_cot        3235 non-null   object
 11  prompt_icl        3235 non-null   object
 12  prompt_icl_cot    3235 non-null   object
dtypes: object(13)
memory usage: 328.7+ KB
None

In [18]:
# View the first few rows of the dataset
tasks_data_df[tasks_data_df['task_type']=='piqa'].head(3)

,task_type,task_format,question,label,gold,corpus,rationale,knowledge,split,prompt_zero_shot,prompt_cot,prompt_icl,prompt_icl_cot
512,piqa,multiple_choice,"To remove a dandelion from the ground, you can...",A,Use your fingers to pick the dandelion,"To remove a dandelion from the ground, you can...",Explanation: \nTo determine the best option f...,Dandelions can be removed from the ground by u...,train,Question: To remove a dandelion from the groun...,Question: To remove a dandelion from the groun...,Question: To cut circles out of dough without ...,Question: To cut circles out of dough without ...
513,piqa,multiple_choice,How to Make a Snowy Paper Christmas Tree\nOpti...,A,You can make a Snowy Paper Christmas Tree by f...,How to Make a Snowy Paper Christmas Tree You c...,Explanation: \nThe question asks how to make ...,"To create a snowy paper Christmas tree, cut th...",train,Question: How to Make a Snowy Paper Christmas ...,Question: How to Make a Snowy Paper Christmas ...,Question: To smooth the edge of the bar stool ...,Question: To smooth the edge of the bar stool ...
514,piqa,multiple_choice,What if I have a pimple that is too painful to...,B,Place the pimple under hot water for 10 min. t...,What if I have a pimple that is too painful to...,Explanation: \nWhen dealing with a painful pi...,Applying hot water to a painful pimple for 10 ...,train,Question: What if I have a pimple that is too ...,Question: What if I have a pimple that is too ...,Question: How to crush oreos using the food pr...,Question: How to crush oreos using the food pr...

In [19]:
print(tasks_data_df[tasks_data_df['task_type']=='piqa'].iloc[1,7])

To create a snowy paper Christmas tree, cut three descending-sized circles with wavy edges from paper, make a triangular notch in each, roll them into cones secured with tape or glue, and stack them from largest to smallest, fixing them in place with glue.